name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release_cli:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Fetch unshallow
        run: |
          git fetch --prune --tags --unshallow
          echo $(git describe --tags --always --first-parent)

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Create CLI dist zip
        run: ./gradlew :modsman-cli:distZip --info --stacktrace

      - name: Create PackUtil jar
        run: ./gradlew :modsman-packutil:build --info --stacktrace

      - uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        id: get_tag

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Modsman v${{ github.ref }}
          draft: false
          prerelease: true

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./modsman-cli/build/distributions/modsman-cli-${{ steps.get_tag.outputs.tag }}.zip
          asset_name: modsman-cli-${{ steps.get_tag.outputs.tag }}.zip
          asset_content_type: application/zip

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./modsman-packutil/build/libs/modsman-packutil-${{ steps.get_tag.outputs.tag }}.jar
          asset_name: modsman-packutil-${{ steps.get_tag.outputs.tag }}.jar
          asset_content_type: application/java-archive
